#pragma once

//----- BG ADDRESSES -----
#define LEVEL_PAL_SLOT 0
#define LEVEL_MAP_ADDR 0x3000
#define LEVEL_GFX_ADDR 0x4000

#define DIVIDER_PAL_SLOT 1
#define DIVIDER_MAP_ADDR 0x0000
#define DIVIDER_GFX_ADDR 0x2000

//----- SPRITE ADDRESSES -----
#define SPRITE1_ADDR_OFFSET 0x0000
